name: Quality & Deploy

on: push

jobs:
  quality-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

  deploy-vercel:
    runs-on: ubuntu-latest

    needs: [quality-gate]
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Create .vercel
        run: mkdir .vercel; echo '{"orgId":"A5Qp2vEaFQGDiB9hgEUnbOma","projectId":"prj_1uxxjRvPG31c3DS3RrReYM5nXkwG"}' > .vercel/project.json;

      - name: Deploy on Vercel
        run: vercel deploy -t ${{ secrets.VERCEL_TOKEN }} --prod
